version: "3"

services:
  smartxchange-db:
    image: mysql:5.7
    container_name: smartxchange-db-prod
    restart: always
    ports:
      - "3320:3306"
    environment:
      DATABASE_HOST: smartxchange-db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: smartxchange
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - smartxchange-mysql-volume:/var/lib/mysql
    networks:
      - smartxchange-mysql-compose-network

  smartxchange-backend:
    image: robertomourato/ldso-t3g3:backend-prod
    build: ./../../back-end
    command: npm start
    container_name: smartxchange-backend-prod
    ports:
      - "3400:3000"
    depends_on:
      - smartxchange-db
    links:
      - smartxchange-db
    volumes:
      - .:/usr/app/backend
    restart: on-failure

  smartxchange-frontend:
    image: robertomourato/ldso-t3g3:frontend-prod
    restart: always
    container_name: smartxchange-frontend-prod
    build: ./../../front-end
    volumes:
      - .:/usr/app/frontend
    ports:
       - 80:4200
    depends_on:
      - smartxchange-backend 

networks:
  smartxchange-mysql-compose-network:
    driver: bridge
volumes:
  smartxchange-mysql-volume: