image: node:latest

stages:
  - build
  - code_analysis
  - test
  - staging
  - production

cache:
  paths:
    - back-end/node_modules/

install_dependencies:
  stage: build
  script:
    - cd back-end
    - npm install
  artifacts:
    paths:
      - back-end/node_modules/

#linting:
#  stage: code_analysis
#  script:
#    - cd back-end
#    - npm run lint

testing:
  stage: test
  script:
    - cd back-end
    - npm test
