stages:
  - install-dependencies
  - security
  - code-analysis
  - test
  - build
  - deploy

cache:
  paths:
    - back-end/node_modules/
    - front-end/node_modules/

installing-dependencies:
  stage: install-dependencies
  image: node:latest
  script:
    - cd back-end
    - npm install
    - cd ../front-end
    - npm install
    - npm install -g @angular/cli@latest
  artifacts:
    paths:
      - back-end/node_modules/
      - front-end/node_modules/

checking-security:
  stage: security
  image: node:latest
  script:
    - cd back-end
    - npm audit
    - cd ../front-end
    - npm audit

linting:
  stage: code-analysis
  image: node:latest
  script:
    - cd back-end
    - npm run lint
    - cd ../front-end
    - npm install -g @angular/cli@latest
    - ng lint


testing:
  stage: test
  image: node:latest
  script:
    - cd back-end
    - npm test
    #- cd ../front-end
    #- ng test

building-staging:
  stage: build
  services:
    - docker:18-dind
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd back-end
    - docker build -t $CI_REGISTRY_IMAGE/back-end:staging .
    - docker push $CI_REGISTRY_IMAGE/back-end:staging
    - cd ../front-end
    - docker build -t $CI_REGISTRY_IMAGE/front-end:staging .
    - docker push $CI_REGISTRY_IMAGE/front-end:staging
  #only:
  #  - merge_request
  #except:
  #  - master

building-production:
  stage: build
  services:
    - docker:18-dind
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd back-end
    - docker build -t $CI_REGISTRY_IMAGE/back-end:staging .
    - docker push $CI_REGISTRY_IMAGE/back-end:staging
    - cd ../front-end
    - docker build -t $CI_REGISTRY_IMAGE/front-end:staging .
    - docker push $CI_REGISTRY_IMAGE/front-end:staging
  only:
    - master

#staging:
#  type: deploy
#  stage: staging
#  script:

#production:
#  type: deploy
#  stage: production
#  script:
#  only:
#    - master