stages:
  - install-dependencies
  - security
  - code_analysis
  - test
  - build
  - deploy

cache:
  paths:
    - back-end/node_modules/
    - front-end/node_modules/

installing-dependencies:
  stage: install-dependencies
  image: node:latest
  script:
    - cd back-end
    - npm install
    - cd ../front-end
    - npm install
    - npm install -g @angular/cli@latest
  artifacts:
    paths:
      - back-end/node_modules/
      - front-end/node_modules/

checking-security:
  stage: security
  image: node:latest
  script:
    - cd back-end
    - npm audit
    - cd ../front-end
    - npm audit

linting:
  stage: code_analysis
  image: node:latest
  script:
    - cd back-end
    - npm run lint
    - cd ../front-end
    - npm install -g @angular/cli@latest
    - ng lint


testing:
  stage: test
  image: node:latest
  script:
    - cd back-end
    - npm test
    #- cd ../front-end
    #- ng test

#staging:
#  type: deploy
#  stage: staging
#  script:

#production:
#  type: deploy
#  stage: production
#  script:
#  only:
#    - master