version: "3"


  #app - name container´
  #build - location dockerfile "." dot is root
  #command start when container is uo
  #basically is a mirror of project
  #ports - port of container : port of localhost
services:
  smartxchange-back-end:
    build: .
    command: npm start
    container_name: smartxchange-back-end
    restart: always
    ports:
      - "3400:3000"
    volumes:
      - .:/usr/app  
