version: "2"
services:
  smartxchange-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=smartxchange
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MAX_CONNECTIONS=512
      #- TZ=${MYSQL_TIMEZONE}
    ports:
      - "3320:3306"
    volumes:
      - smartxchange-mysql-volume:/var/lib/mysql
    networks:
      - smartxchange-mysql-compose-network

  smartxchange-adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080
    networks:
      - smartxchange-mysql-compose-network

networks:
  smartxchange-mysql-compose-network:
    driver: bridge
volumes:
  smartxchange-mysql-volume:
